// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string):Promise<Error>;

export function DisConnect():Promise<void>;

export function Send(arg1:string):Promise<Error>;
