// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function Connect(arg1:string):Promise<Error>;

export function DisConnect():Promise<void>;

export function RemoteAddr():Promise<string>;

export function Send(arg1:string):Promise<Error>;

export function SendMessage(arg1:Array<number>):Promise<void>;
