// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['service']['MudService']['Close']();
}

export function Connect(arg1) {
  return window['go']['service']['MudService']['Connect'](arg1);
}

export function DisConnect() {
  return window['go']['service']['MudService']['DisConnect']();
}

export function RemoteAddr() {
  return window['go']['service']['MudService']['RemoteAddr']();
}

export function Send(arg1) {
  return window['go']['service']['MudService']['Send'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['service']['MudService']['SendMessage'](arg1);
}
